import './globals.css'
import Navbar from './navbar.js';
import Footer from './footer.js';

export const metadata = {
  title: 'DesiTech Solutions',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <main className="flex min-h-screen flex-col justify-between pt-5 max-md:pt-3">
          <Navbar />
          { children }
          <Footer />
        </main>
      </body>
    </html>
  )
}
